import OAI.GroupTheory.ArtinCAT0.Main

/-!
# An 11-generator Artin group with no geometric CAT(0) action

Letters (as `Fin 11`): 0 = a, 1 = b, 2 = c, 3 = e, 4..10 = x1..x7.

* `a, b, x1, ..., x7` is a 10-strand braid chain.
* `c` braids with `a`, `b`, `x2`, commutes with `x1`, `x3`, `e`.
* `e` commutes with `a`, `b`, `c`.
* every other pair has label infinity.
-/

namespace OAI
namespace ArtinCAT0
namespace Eleven

open scoped Classical

/-! ## The matrix -/

/-- Position of a chain letter in the chain `a, b, x1, ..., x7`. -/
def chainPos (i : ℕ) : ℕ := if i < 2 then i else i - 2

def isChain (i : ℕ) : Bool := i ≠ 2 && i ≠ 3

/-- Labels, with `0` standing for infinity. -/
def lab (s t : Fin 11) : ℕ :=
  if s = t then 1
  else if isChain s.val && isChain t.val then
    (if chainPos s.val + 1 = chainPos t.val ∨ chainPos t.val + 1 = chainPos s.val then 3 else 2)
  else if s.val = 2 ∨ t.val = 2 then
    (let k := if s.val = 2 then t.val else s.val
     if k = 0 ∨ k = 1 ∨ k = 5 then 3 else if k = 3 ∨ k = 4 ∨ k = 6 then 2 else 0)
  else
    (let k := if s.val = 3 then t.val else s.val
     if k = 0 ∨ k = 1 then 2 else 0)

def M11 (s t : Fin 11) : Label := if lab s t = 0 then ⊤ else (lab s t : Label)

lemma lab_symm : ∀ s t : Fin 11, lab s t = lab t s := by decide
lemma lab_values : ∀ s t : Fin 11, lab s t = 0 ∨ lab s t = 1 ∨ lab s t = 2 ∨ lab s t = 3 := by
  decide
lemma lab_one : ∀ s t : Fin 11, lab s t = 1 → s = t := by decide
lemma lab_diag : ∀ s : Fin 11, lab s s = 1 := by decide

lemma M11_nat {s t : Fin 11} {n : ℕ} (h : M11 s t = (n : Label)) : lab s t = n ∧ n ≠ 0 := by
  unfold M11 at h
  split_ifs at h with h0
  · exact False.elim (WithTop.top_ne_coe h)
  · exact ⟨by exact_mod_cast h, fun hn => h0 (by subst hn; exact_mod_cast h)⟩

theorem M11_symmetric (s t : Fin 11) : M11 s t = M11 t s := by
  unfold M11; rw [lab_symm]
theorem M11_diagonal (s : Fin 11) : M11 s s = 1 := by
  unfold M11; rw [lab_diag]; simp
theorem M11_values (s t : Fin 11) (h : s ≠ t) :
    M11 s t = 2 ∨ M11 s t = 3 ∨ M11 s t = ⊤ := by
  unfold M11
  rcases lab_values s t with h0 | h1 | h2 | h3
  · simp [h0]
  · exact False.elim (h (lab_one s t h1))
  · simp [h2]
  · simp [h3]

/-! ## A general lift out of an Artin group with labels in {1,2,3,∞} -/

section Lift
variable {S H : Type*} [Group H]

def artinLift (M : S → S → Label) (v : S → H)
    (hv : ∀ s t (n : ℕ), M s t = n →
      (s = t) ∨ (n = 2 ∧ Commute (v s) (v t)) ∨ (n = 3 ∧ v s * v t * v s = v t * v s * v t) ∨
        (n = 1 ∧ v s = v t)) :
    ArtinGroup M →* H :=
  PresentedGroup.toGroup (f := v) (by
    rintro r ⟨s, t, n, hn, rfl⟩
    simp only [map_mul, map_inv, mul_inv_eq_one]
    rcases hv s t n hn with rfl | ⟨rfl, h⟩ | ⟨rfl, h⟩ | ⟨rfl, h⟩
    · rfl
    · simpa [alternating, map_mul] using h.eq
    · simpa [alternating, map_mul, mul_assoc] using h
    · simpa [alternating] using h)

@[simp] lemma artinLift_of (M : S → S → Label) (v : S → H) (hv) (s : S) :
    artinLift M v hv (PresentedGroup.of s) = v s := PresentedGroup.toGroup.of _

end Lift

/-- Relations of `M11` in terms of `lab`. -/
lemma M11_cases {s t : Fin 11} {n : ℕ} (h : M11 s t = (n : Label)) :
    s = t ∨ (n = 2 ∧ lab s t = 2) ∨ (n = 3 ∧ lab s t = 3) := by
  obtain ⟨hl, hn⟩ := M11_nat h
  rcases lab_values s t with h0 | h1 | h2 | h3
  · exact False.elim (hn (hl.symm.trans h0))
  · exact Or.inl (lab_one s t h1)
  · exact Or.inr (Or.inl ⟨by omega, h2⟩)
  · exact Or.inr (Or.inr ⟨by omega, h3⟩)

abbrev MainGroup := ArtinGroup M11
abbrev mainGen (s : Fin 11) : MainGroup := PresentedGroup.of s

lemma main_braid (s t : Fin 11) (h : lab s t = 3) :
    mainGen s * mainGen t * mainGen s = mainGen t * mainGen s * mainGen t :=
  artin_braid M11 s t (by unfold M11; simp [h])

lemma main_commute (s t : Fin 11) (h : lab s t = 2) : Commute (mainGen s) (mainGen t) :=
  artin_commute M11 s t (by unfold M11; simp [h])

/-! ## The subgroup without the sentinel -/

def ι (i : Fin 10) : Fin 11 := if i.val < 3 then ⟨i.val, by omega⟩ else ⟨i.val + 1, by omega⟩

def M0 (i j : Fin 10) : Label := M11 (ι i) (ι j)

abbrev G0 := ArtinGroup M0
abbrev g0Gen (i : Fin 10) : G0 := PresentedGroup.of i

lemma ι_injective : Function.Injective ι := by decide

lemma g0_braid (i j : Fin 10) (h : lab (ι i) (ι j) = 3) :
    g0Gen i * g0Gen j * g0Gen i = g0Gen j * g0Gen i * g0Gen j :=
  artin_braid M0 i j (by unfold M0 M11; simp [h])

lemma g0_commute (i j : Fin 10) (h : lab (ι i) (ι j) = 2) : Commute (g0Gen i) (g0Gen j) :=
  artin_commute M0 i j (by unfold M0 M11; simp [h])

/-- The triangle subgroup of `G0`, generated by `a, b, c`. -/
def t0 : TriangleGroup →* G0 := triangleLift (fun k => g0Gen ⟨k.val, by omega⟩) (by
  intro k
  apply g0_braid
  fin_cases k <;> decide)

@[simp] lemma t0_gen (k : Fin 3) : t0 (triangleGen k) = g0Gen ⟨k.val, by omega⟩ :=
  triangleLift_gen _ _ _

/-! ## The reflection representation, used to show `x3` is not in the triangle subgroup -/

section Reflection

abbrev V := Fin 10 → ℚ

def Bm (i j : Fin 10) : ℚ :=
  if i = j then 1 else if lab (ι i) (ι j) = 3 then -1/2 else 0

def ip (i : Fin 10) (w : V) : ℚ := ∑ k, Bm i k * w k

def reflFun (i : Fin 10) (w : V) : V := w - (2 * ip i w) • Pi.single i 1

lemma ip_sub (i : Fin 10) (w u : V) : ip i (w - u) = ip i w - ip i u := by
  simp [ip, mul_sub, Finset.sum_sub_distrib]

lemma ip_smul_single (i j : Fin 10) (c : ℚ) : ip i (c • Pi.single j 1) = c * Bm i j := by
  simp [ip, Pi.single_apply, Finset.sum_ite_eq', mul_comm]

lemma ip_refl (k i : Fin 10) (w : V) : ip k (reflFun i w) = ip k w - 2 * ip i w * Bm k i := by
  rw [reflFun, ip_sub, ip_smul_single]

lemma Bm_self (i : Fin 10) : Bm i i = 1 := by simp [Bm]

lemma reflFun_involutive (i : Fin 10) : Function.Involutive (reflFun i) := by
  intro w
  have h := ip_refl i i w
  rw [Bm_self] at h
  rw [show reflFun i (reflFun i w) = reflFun i w - (2 * ip i (reflFun i w)) • Pi.single i 1
    from rfl, h]
  funext k
  simp only [reflFun, Pi.sub_apply, Pi.smul_apply, smul_eq_mul]
  ring

def refl (i : Fin 10) : Equiv.Perm V := (reflFun_involutive i).toPerm _

@[simp] lemma refl_apply (i : Fin 10) (w : V) : refl i w = reflFun i w := rfl

lemma refl_commute (i j : Fin 10) (hij : Bm i j = 0) (hji : Bm j i = 0) :
    Commute (refl i) (refl j) := by
  apply Equiv.ext
  intro w
  change reflFun i (reflFun j w) = reflFun j (reflFun i w)
  have h1 := ip_refl i j w
  have h2 := ip_refl j i w
  rw [hij] at h1; rw [hji] at h2
  rw [show reflFun i (reflFun j w) = reflFun j w - (2 * ip i (reflFun j w)) • Pi.single i 1
    from rfl, h1,
    show reflFun j (reflFun i w) = reflFun i w - (2 * ip j (reflFun i w)) • Pi.single j 1
    from rfl, h2]
  funext k
  simp only [reflFun, Pi.sub_apply, Pi.smul_apply, smul_eq_mul]
  ring

lemma refl_braid (i j : Fin 10) (hij : Bm i j = -1/2) (hji : Bm j i = -1/2) :
    refl i * refl j * refl i = refl j * refl i * refl j := by
  apply Equiv.ext
  intro w
  change reflFun i (reflFun j (reflFun i w)) = reflFun j (reflFun i (reflFun j w))
  simp only [reflFun, ip_sub, ip_smul_single, Bm_self, hij, hji]
  funext k
  simp only [Pi.sub_apply, Pi.smul_apply, smul_eq_mul]
  ring

lemma Bm_of_lab3 (i j : Fin 10) (h : lab (ι i) (ι j) = 3) : Bm i j = -1/2 := by
  have hne : i ≠ j := by
    rintro rfl
    rw [lab_diag] at h
    exact absurd h (by norm_num)
  simp [Bm, hne, h]

lemma Bm_of_lab2 (i j : Fin 10) (h : lab (ι i) (ι j) = 2) : Bm i j = 0 := by
  have hne : i ≠ j := by
    rintro rfl
    rw [lab_diag] at h
    exact absurd h (by norm_num)
  simp [Bm, hne, h]

def ψ : G0 →* Equiv.Perm V := artinLift M0 refl (by
  intro s t n hn
  rcases M11_cases hn with h | ⟨rfl, h⟩ | ⟨rfl, h⟩
  · exact Or.inl (ι_injective h)
  · exact Or.inr (Or.inl ⟨rfl, refl_commute s t (Bm_of_lab2 s t h)
      (Bm_of_lab2 t s (by rw [lab_symm]; exact h))⟩)
  · exact Or.inr (Or.inr (Or.inl ⟨rfl, refl_braid s t (Bm_of_lab3 s t h)
      (Bm_of_lab3 t s (by rw [lab_symm]; exact h))⟩)))

@[simp] lemma ψ_gen (i : Fin 10) : ψ (g0Gen i) = refl i := artinLift_of _ _ _ _

/-- Permutations that change only the coordinates of `a, b, c`. -/
def fixesRest : Subgroup (Equiv.Perm V) where
  carrier := {g | ∀ w k, 3 ≤ k.val → g w k = w k}
  one_mem' := fun _ _ _ => rfl
  mul_mem' := by
    intro g h hg hh w k hk
    change g (h w) k = w k
    rw [hg _ _ hk, hh _ _ hk]
  inv_mem' := by
    intro g hg w k hk
    have := hg (g⁻¹ w) k hk
    rw [← Equiv.Perm.mul_apply, mul_inv_cancel, Equiv.Perm.one_apply] at this
    exact this.symm

lemma refl_fixesRest (i : Fin 10) (hi : i.val < 3) : refl i ∈ fixesRest := by
  intro w k hk
  have hne : k ≠ i := by
    intro h; subst h; omega
  simp [reflFun, Pi.single_apply, hne]

lemma t0_range_le : (ψ.comp t0).range ≤ fixesRest := by
  rintro _ ⟨t, rfl⟩
  let C := fixesRest.comap (ψ.comp t0)
  have hgen (k : Fin 3) : PresentedGroup.of (rels := triangleRelators) k ∈ C := by
    change ψ (t0 (triangleGen k)) ∈ fixesRest
    rw [t0_gen, ψ_gen]
    exact refl_fixesRest _ (by simp)
  exact PresentedGroup.generated_by triangleRelators C hgen t

/-- `x3` (index 5 in `G0`) does not lie in the triangle subgroup. -/
theorem x3_not_in_triangle : g0Gen 5 ∉ t0.range := by
  rintro ⟨t, ht⟩
  have hmem : ψ (t0 t) ∈ fixesRest := t0_range_le ⟨t, rfl⟩
  rw [ht, ψ_gen] at hmem
  have h := hmem (Pi.single 5 1) 5 (by decide)
  simp [reflFun, ip, Bm, Pi.single_apply] at h

end Reflection

end Eleven
end ArtinCAT0
end OAI
